server:
  port: 8183
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
spring:
  datasource:
    url: jdbc:h2:mem:basemsdb;MODE=MySQL
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    platform: h2
  jpa:
    hibernate:
      ddl-auto: create
  profiles:
    active: dev