server:
  port: 8183
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  datasource:
    url: jdbc:h2:mem:basemsdb;MODE=MySQL
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    platform: h2
  jpa:
    hibernate:
      ddl-auto: create
  profiles:
    active: dev