server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
zuul:
  routes:
    hello: /hello/**
    security: /security/**
    product: /product/**
    category: /category/**
    email: /email/**