server:
  port: 8184
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  profiles:
    active: dev
  mail:
    host: smtp.gmail.com
    username: your.username@gmail.com
    password: your-token
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          ssl:
            enable: true